### ISSUE TITLE
Error: Could not retrieve version of the latest MPC-HC pre-release

### ISSUE THREAD

**Issue by Rydako** [nikola/htpc-updater#1]
Using the flag
--install-pre-release =mpchc

To update to the nightly builds of MPC-HC fails with this error. Standard build seems to be identified fine.

**Comment by nikola** [comment]
Fixed in 0.8.2.

**Comment by Trent306** [comment]
Is it possible to update this tool to download 64-bit versions of MPC-HC and LAV Filters? The entire playback chain (LAV Filters -> MPC-HC -> madVR) is now available as 64-bit software.

**Comment by nikola** [comment]
Should be possible, but I haven't touched the codebase in a while. If I recall correctly, the reason why 64-bit wasn't supported from the beginning is because detecting the currently installed version of components isn't as straightforward for 64-bit as it for 32-bit.
