### ISSUE TITLE
permission to use 'frozen' PyPI package name?

### ISSUE THREAD

**Issue by mcandre** [nikola/htpc-updater#2]
Hi Nikola!

I'm working on a Python package for freezing arbitrary objects, and I was wondering if you would allow me to use the 'frozen' package name? You uploaded an unreleased package in January, but it hasn't seen much activity since then.

Would you be okay if I took that name for my project?

**Comment by nikola** [comment]
Actually, I do plan to publish my own frozen project on GitHub and PyPi in the next few months (right now it's a private repository on GitHub), so I will need to use the 'frozen' package name on PyPi.

**Comment by mcandre** [comment]
Thanks for the quick response! I'll change my package name to something else.
