### ISSUE TITLE
htpc-updater.py not working/incompatible

### ISSUE THREAD

**Issue by AndreCarini** [nikola/htpc-updater#3]
Thanks for developing this. The pre-compiled exe runs correctly on my machine but the .py script throws a multitude of errors when interpreted by Python 2.7.11. Are there any known issues?

Some of the errors involved:

- updater.lib non-existant, fixed by cloning your other repo linked within /src/ and then dropping the updaterlib folder inside /Lib, next to /Scripts, and then removing the dot from the reference inside the script;
- windll being undefined, fixed by changing to import everything from ctype;
- log color BLACK or RED also undefined, fixed by manually defining their bit values beforehand;
- setLogger being undefined (is it defined elsewhere?)

Seems like I'm doing something wrong or the script needs to be updated to support Windows 10 x64 and/or 2.7.11. Couldn't find much help around so I'm opening an issue here..

**Comment by nikola** [comment]
You forgot to pull the submodule https://github.com/nikola/updaterlib therefore you get all these errors. There is actually a script in the repo that updates the submodule for you:

https://github.com/nikola/htpc-updater/blob/master/update-submodules.bat

**Comment by AndreCarini** [comment]
Hi @nikola. Thanks for the quick response.

I couldn't pull the src/updater submodule using your bat (the command runs but nothing happens) but I managed to do it with 'git submodule update --init --recursive'.

The htpc-updater.py script now initializes but I get this error:

```
Latest release version of MPC-HC: 1.7.10
Installed version: 1.7.9
        C:\Program Files (x86)\MPC-HC
Identifying filename of MPC-HC download ...
Traceback (most recent call last):
  File "D:\Development\Python27\Scripts\htpc-updater\src\htpc-updater.py", line 223, in <module>
    _updateComponents(options)
  File "D:\Development\Python27\Scripts\htpc-updater\src\htpc-updater.py", line 122, in _updateComponents
    getattr(instance, 'installLatest%sReleaseVersion' % infix)(latestVersion, detectedInstallationPath, silent)
  File "D:\Development\Python27\Scripts\htpc-updater\src\updater\lib.py", line 138, in mpcHc_installLatestReleaseVersion
    initialUrl = re.search(url, html).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

Press ENTER to exit ...
```

Either way, I've published some suggested changes on the readme for unexperienced users like myself
